### ISSUE TITLE
import fail

### ISSUE THREAD

**Issue by Doldak** [Artemis-RGB/Artemis.Plugins.Wrappers#4]
i get a failed to try import the Razer Wrapper
![grafik](https://user-images.githubusercontent.com/86937864/208790107-f05145cf-4885-4d00-94d3-117c712a19b6.png)
Artemis are Up To Date.

**Comment by Doldak** [comment]
```
2022-12-22 04:01:48.852 [WRN] [Artemis.Core.Services.PluginManagementService] Plugin exception
Artemis.Core.ArtemisPluginException: Failed to load plugin at C:\ProgramData\Artemis\Plugins\Artemis.Plugins.Wrappers.Razer-02ed2899
 ---> Artemis.Core.ArtemisPluginException: Failed to initialize the plugin assembly
 ---> System.AggregateException: One or more errors occurred. (Could not load file or assembly 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.) (Could not load file or assembly 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.) (Could not load file or assembly 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.) (Could not load file or assembly 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.) (Could not load file or assembly 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.) (Could not load file or assembly 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.) (Could not load file or assembly 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.) (Could not load file or assembly 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.)
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.
File name: 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) System.IO.FileNotFoundException: Could not load file or assembly 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.
File name: 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'<---

 ---> (Inner Exception #2) System.IO.FileNotFoundException: Could not load file or assembly 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.
File name: 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'<---

 ---> (Inner Exception #3) System.IO.FileNotFoundException: Could not load file or assembly 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.
File name: 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'<---

 ---> (Inner Exception #4) System.IO.FileNotFoundException: Could not load file or assembly 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.
File name: 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'<---

 ---> (Inner Exception #5) System.IO.FileNotFoundException: Could not load file or assembly 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.
File name: 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'<---

 ---> (Inner Exception #6) System.IO.FileNotFoundException: Could not load file or assembly 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.
File name: 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'<---

 ---> (Inner Exception #7) System.IO.FileNotFoundException: Could not load file or assembly 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.
File name: 'Artemis.Core, Version=1.2022.1114.2, Culture=neutral, PublicKeyToken=null'<---

   --- End of inner exception stack trace ---
   at Artemis.Core.Services.PluginManagementService.LoadPlugin(DirectoryInfo directory) in D:\a\1\s\Artemis\src\Artemis.Core\Services\PluginManagementService.cs:line 361
   at Artemis.Core.Services.PluginManagementService.LoadPlugins(Boolean isElevated) in D:\a\1\s\Artemis\src\Artemis.Core\Services\PluginManagementService.cs:line 232
   --- End of inner exception stack trace ---
```
